-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 14:22:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema heroku_3b4f4710d6d9b37
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_3b4f4710d6d9b37
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_3b4f4710d6d9b37` DEFAULT CHARACTER SET utf8 ;
USE `heroku_3b4f4710d6d9b37` ;

-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_rank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_rank` (
  `id` INT NOT NULL,
  `name` ENUM("Silver", "Gold", "Platinum", "Diamon") NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_shop` (
  `id` INT NOT NULL,
  `name` NVARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_user` (
  `id` INT NOT NULL,
  `username` VARCHAR(80) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `password` TEXT NULL,
  `tbl_rank_id` INT NULL,
  `tbl_shop_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) ,
  INDEX `fk_tbl_user_tbl_rank1_idx` (`tbl_rank_id` ASC) ,
  INDEX `fk_tbl_user_tbl_shop1_idx` (`tbl_shop_id` ASC) ,
  CONSTRAINT `fk_tbl_user_tbl_rank1`
    FOREIGN KEY (`tbl_rank_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_rank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_tbl_shop1`
    FOREIGN KEY (`tbl_shop_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(255) NOT NULL,
  `city` NVARCHAR(255) NULL,
  `address` MEDIUMTEXT NULL,
  `gender` TINYINT(1) NULL,
  `dob` DATETIME NULL,
  `tbl_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_account_tbl_user1_idx` (`tbl_user_id` ASC) ,
  CONSTRAINT `fk_tbl_account_tbl_user1`
    FOREIGN KEY (`tbl_user_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_category` (
  `id` INT NOT NULL,
  `name` NVARCHAR(255) NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(13,2) UNSIGNED NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `stock` SMALLINT UNSIGNED NOT NULL,
  `sku` VARCHAR(45) NULL,
  `tbl_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC) ,
  INDEX `fk_tbl_product_tbl_category1_idx` (`tbl_category_id` ASC) ,
  CONSTRAINT `fk_tbl_product_tbl_category1`
    FOREIGN KEY (`tbl_category_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_payment` (
  `id` INT NOT NULL,
  `name` NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`ref_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`ref_order_status` (
  `code` VARCHAR(1) NOT NULL,
  `order_status` ENUM('WAITING', 'SHIPPING', 'DELIVERED') NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_discount` (
  `code` INT NOT NULL,
  `quantity` INT NULL,
  `discount_number` DECIMAL(3,2) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_status_code` VARCHAR(45) NOT NULL,
  `date_order_placed` DATETIME NULL,
  `tbl_payment_id` INT NOT NULL,
  `ref_order_status_code` VARCHAR(1) NOT NULL,
  `tbl_discount_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_order_tbl_payment1_idx` (`tbl_payment_id` ASC) ,
  INDEX `fk_tbl_order_ref_order_status1_idx` (`ref_order_status_code` ASC) ,
  INDEX `fk_tbl_order_tbl_discount1_idx` (`tbl_discount_code` ASC) ,
  CONSTRAINT `fk_tbl_order_tbl_payment1`
    FOREIGN KEY (`tbl_payment_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_order_ref_order_status1`
    FOREIGN KEY (`ref_order_status_code`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`ref_order_status` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_order_tbl_discount1`
    FOREIGN KEY (`tbl_discount_code`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_discount` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`ref_order_item_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`ref_order_item_status` (
  `code` VARCHAR(1) NOT NULL,
  `order_item_status` ENUM('WAITING', 'ACCEPT', 'REJECT') NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_order_item` (
  `id` INT NOT NULL,
  `quantity` SMALLINT NULL,
  `tbl_order_id` INT NOT NULL,
  `tbl_product_id` INT NOT NULL,
  `ref_order_item_status_code` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_order_item_tbl_order1_idx` (`tbl_order_id` ASC) ,
  INDEX `fk_tbl_order_item_tbl_product1_idx` (`tbl_product_id` ASC) ,
  INDEX `fk_tbl_order_item_ref_order_item_status1_idx` (`ref_order_item_status_code` ASC) ,
  CONSTRAINT `fk_tbl_order_item_tbl_order1`
    FOREIGN KEY (`tbl_order_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_order_item_tbl_product1`
    FOREIGN KEY (`tbl_product_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_order_item_ref_order_item_status1`
    FOREIGN KEY (`ref_order_item_status_code`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`ref_order_item_status` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_product_image` (
  `id` INT NOT NULL,
  `image` VARCHAR(255) NULL,
  `tbl_product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_product_image_tbl_product1_idx` (`tbl_product_id` ASC) ,
  CONSTRAINT `fk_tbl_product_image_tbl_product1`
    FOREIGN KEY (`tbl_product_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_product_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_product_description` (
  `tbl_product_id` INT NOT NULL,
  INDEX `fk_tbl_product_description_tbl_product1_idx` (`tbl_product_id` ASC) ,
  CONSTRAINT `fk_tbl_product_description_tbl_product1`
    FOREIGN KEY (`tbl_product_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`tbl_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`tbl_permission` (
  `id` INT NOT NULL,
  `controller` VARCHAR(255) NOT NULL,
  `action` ENUM('READ') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`ref_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`ref_role_permission` (
  `id` INT NOT NULL,
  `is_enabled` TINYINT(1) NULL DEFAULT 0,
  `tbl_role_id` INT NOT NULL,
  `tbl_permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ref_role_permission_tbl_role1_idx` (`tbl_role_id` ASC) ,
  INDEX `fk_ref_role_permission_tbl_permission1_idx` (`tbl_permission_id` ASC) ,
  CONSTRAINT `fk_ref_role_permission_tbl_role1`
    FOREIGN KEY (`tbl_role_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_role_permission_tbl_permission1`
    FOREIGN KEY (`tbl_permission_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`ref_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`ref_user_role` (
  `id` INT NOT NULL,
  `tbl_user_id` INT NOT NULL,
  `tbl_role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ref_user_role_tbl_user1_idx` (`tbl_user_id` ASC) ,
  INDEX `fk_ref_user_role_tbl_role1_idx` (`tbl_role_id` ASC) ,
  CONSTRAINT `fk_ref_user_role_tbl_user1`
    FOREIGN KEY (`tbl_user_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_user_role_tbl_role1`
    FOREIGN KEY (`tbl_role_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_3b4f4710d6d9b37`.`ref_shop_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_3b4f4710d6d9b37`.`ref_shop_product` (
  `id` INT NOT NULL,
  `tbl_product_id` INT NOT NULL,
  `tbl_farm_id` INT NOT NULL,
  `tbl_shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ref_farm_product_tbl_product1_idx` (`tbl_product_id` ASC) ,
  INDEX `fk_ref_shop_product_tbl_shop1_idx` (`tbl_shop_id` ASC) ,
  CONSTRAINT `fk_ref_farm_product_tbl_product1`
    FOREIGN KEY (`tbl_product_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_shop_product_tbl_shop1`
    FOREIGN KEY (`tbl_shop_id`)
    REFERENCES `heroku_3b4f4710d6d9b37`.`tbl_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
